services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Sword\SwordBundle\:
        resource: '../src/'
        exclude:
            - '../src/Attribute/'
            - '../src/DependencyInjection/'
            - '../src/Helper/'
